-- arquivo para insercao nas tabelas do banco de dados

BEGIN TRANSACTION;
INSERT INTO `Tag` VALUES (1,'IFGW',3);
INSERT INTO `Tag` VALUES (2,'IC',2);
INSERT INTO `Tag` VALUES (3,'Bandeco',45);
INSERT INTO `Tag` VALUES (4,'pele laranja',30);
INSERT INTO `Tag` VALUES (5,'feio',25);
INSERT INTO `Tag` VALUES (6,'Reitoria',11);
INSERT INTO `Tag` VALUES (7,'Educação Física',2);
INSERT INTO `Spotted` VALUES (1,'Mateus Camilli é um vacilão','2007-01-01 10:00:40',2,NULL);
INSERT INTO `Spotted` VALUES (2,'Italove, te vi no IC ontem... me chama de código-fonte e me compila!','2017-04-04 10:00:00',1004,2);
INSERT INTO `Reage` VALUES (1004,1,'2017-05-05 06:06:06','curtiu');
INSERT INTO `Reage` VALUES (1004,2,'2017-05-05 06:34:02','adorou');
INSERT INTO `Reage` VALUES (2,2,'2017-07-13 07:00:32','adorou');
INSERT INTO `Pessoa` VALUES (1,'Joao Lucas',23);
INSERT INTO `Pessoa` VALUES (2,'Mateus Camilli',20);
INSERT INTO `Pessoa` VALUES (3,'Papa Camilli',40);
INSERT INTO `Pessoa` VALUES (1004,'Italove',21);
INSERT INTO `Local` VALUES (1,'Aula');
INSERT INTO `Local` VALUES (2,'Aula');
INSERT INTO `Local` VALUES (3,'Jantar');
INSERT INTO `Local` VALUES (6,'Ocupação');
INSERT INTO `Fenotipo` VALUES (4,'cor da pele');
INSERT INTO `Fenotipo` VALUES (5,'beleza');
INSERT INTO `Descrita` VALUES (2,1);
INSERT INTO `Descrita` VALUES (2,5);
INSERT INTO `Descrita` VALUES (2,7);
INSERT INTO `Descrita` VALUES (2,4);
INSERT INTO `Descrita` VALUES (1004,2);
INSERT INTO `Descrita` VALUES (2,3);
INSERT INTO `Curso` VALUES (7,'FEF');
INSERT INTO `Comentario` VALUES (1,'Vc que está lendo isso, cadê a nota do ranido?','2017-08-01 03:22:22',2,1004);
INSERT INTO Spotted (id_spot, texto, horário, cita) values (35819, 'Daphiny Lisboa, te vi no arraiá da Feagri e nooossa! Como você é linda <3 Nem vou tentar te elogiar porque nenhum elogio lhe faria realmente justiça. Não tive coragem de puxar papo contigo :( Como faço pra te conhecer, moça linda?', '2017-06-08 08:45:09', 1025)
INSERT INTO Pessoa (nome) VALUES ('Stephan Shih');
INSERT INTO Spotted (id_spot, texto, horário, cita) VALUES (35818, 'stephan você estava uma fofura de chapeuzinho ontem na fj ♥', '2017-06-08 08:45:06', 1026);
INSERT INTO reage (id_pes, id_spot, tipo) VALUES (1024, 35818, 'amei');
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (1, 'GRANDE STEPHAN', '2017-06-08 10:00:00', 35818, 1024);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (2, 'Stephan Shih ish', '2017-06-08 09:44:32', 35818, 1027);
INSERT INTO Pessoa (nome) VALUES ('Fernanda Polidoro');
INSERT INTO Spotted (id_spot, texto, horário, cita) VALUES (35817, 'Fernanda Polidoro, 014 das Sociais. Oi, tudo bem? A gente se conhece há um bom tempo, ainda que você não venha saber quem te mandou isso. Foi muito bom te cruzar de novo pela vida depois de três longos anos no ensino médio sem que acabassemos no vendo após 2010. Fico feliz por te encontrar às vezes, ainda mais depois de anos. Creio que não haja crushs a se declarar nem amores a se morrer, mas, por fim, só isso: fico feliz.', '2017-06-08 08:45:08', 1028);
INSERT INTO Tag (nome, quantidade) VALUES ('Ciências Sociais', 1);
INSERT INTO Curso (id_tag, instituto) VALUES (13, 'IFCH');
INSERT INTO Spotted (id_spot, texto, horário) VALUES (36816, 'Cara, se não fecha antes, difícil fechar durante, depois nem se fala. M 25 anos, procura H 25+ para fechar antes no Ipeixe ;)', '2017-06-08 05:45:30');
INSERT INTO Tag (nome, quantidade) VALUES ('IFCH', 1);
INSERT INTO Local (id_tag, evento) VALUES (12, 'festa');
INSERT INTO Pessoa (nome) VALUES ('Amanda Calixto');
INSERT INTO Spotted (id_spot, texto, horário, cita) VALUES (35815, 'Calixto so queria dizer que voce estava sensacional no Arraia Pena que nunca te encontrei sozinha', '2017-06-08 05:45:26', 1029);
INSERT INTO Pessoa (nome) VALUES ('Felipe Ochinslz');
INSERT INTO Pessoa (nome) VALUES ('Bruno Jorge Renjiffo');
INSERT INTO Pessoa (nome) VALUES ('Victor Hanzir');
INSERT INTO Pessoa (nome) VALUES ('Igor Valente');
INSERT INTO Pessoa (nome) VALUES ('Jas Saldana');
INSERT INTO Pessoa (nome) VALUES ('Vinicius Camargos');
INSERT INTO Pessoa (nome) VALUES ('Manoel Pedro');
INSERT INTO Pessoa (nome) VALUES ('Leandro Pio de Sousa');
INSERT INTO Pessoa (nome) VALUES ('Jonas Custódio');
INSERT INTO Pessoa (nome) VALUES ('Paulo Schink');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1030, 35816, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1031, 35816, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1032, 35816, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1033, 35816, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1034, 35816, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1035, 35816, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1036, 35816, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1037, 35816, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1038, 35816, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1039, 35816, 'curtiu');
INSERT INTO Pessoa (nome) VALUES ('Amanda Gomes');
INSERT INTO Pessoa (nome) VALUES ('Arthur Vilella');
INSERT INTO Pessoa (nome) VALUES ('Júlia Elisa Martins');
INSERT INTO Pessoa (nome) VALUES ('Estefani Costa');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1040, 35815, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1044, 35815, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1029, 35815, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1042, 35815, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1043, 35815, 'curtiu');
INSERT INTO Contem (id_spot, id_tag) VALUES (35815, 8);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (1, 'Amanda Calixto até que demorou dessa vez hahahah', '2017-06-08 09:32:55', 35815, 1043);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (2, 'HAHAHAHAHAHA certeza que foi a Virgínia Oliveira Pires q mandou', '2017-06-08 11:03:42', 35815, 1029);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (1, 'Se elx falasse que quer vc aceitaria porque vc quer, mas como não sabe em que página o outro está, não fala nada com medo da pessoa ir embora. Agora, vamos ser realistas e objetivos aqui? Vc quer e a situação está desconfortável para vc, passou da hora de vc admitir e falar para elx: do jeito que está não funciona para mim, quero namorar. Fala e vê o que acontece.', '2017-06-08 08:54:47', 35822,  1015);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (2, 'Tem um ditado muito lindo que diz: "ou caga, ou desocupa a moita"', '2017-06-08 09:35:21', 35822, 1016);
INSERT INTO Pessoa (nome) VALUES ('Cauê Pinheiro');
INSERT INTO Spotted (id_spot, texto, horário, cita) VALUES (35814, 'Dedico esse spotted pro agroboy Cauê/ Kauê que nas horas vagas trabalha como cupido nos arraiás da Feagri e região hahaha Moço, você foi um anjo comigo. Obrigada de coração ♥', '2017-08-06 05:45:12', 1045);
INSERT INTO Pessoa (nome) VALUES ('Letícia Campos');
INSERT INTO Pessoa (nome) VALUES ('Leandra Marcondes');
INSERT INTO Pessoa (nome) VALUES ('Natalia Ferreira');
INSERT INTO Pessoa (nome) VALUES ('Francini Domingos');
INSERT INTO Pessoa (nome) VALUES ('Mariane Farias');
INSERT INTO Pessoa (nome) VALUES ('Letícia Yumi');
INSERT INTO Pessoa (nome) VALUES ('Gabriela Cesar');
INSERT INTO Pessoa (nome) VALUES ('Gustavo Nagasaka');
INSERT INTO Pessoa (nome) VALUES ('Monique Cain');
INSERT INTO Pessoa (nome) VALUES ('Luana Paschoal');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1045, 35814, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1046, 35814, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1047, 35814, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1048, 35814, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1049, 35814, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1050, 35814, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1051, 35814, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1052, 35814, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1053, 35814, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1054, 35814, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1055, 35814, 'curtiu');
INSERT INTO Pessoa (nome) VALUES ('Nath Medeiros');
INSERT INTO Pessoa (nome) VALUES ('Renato Natalio');
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (1, 'Ta aí o grande Cauê Pinheiro hahaha Gustavo Nagasaka Renato Natalio', '2017-06-08 10:25:39', 35814, 1056);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (2, 'Ooooown Cauê Pinheiro', '2017-06-08 10:39:20', 35814, 1057);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (3, 'Muito bom moço 😍', '2017-06-08 10:43:37', 35814, 1053);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (4, '❤❤❤', '2017-06-08 11:17:46', 35814, 1048);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES (5, 'Grande Cauê Pinheiro', '2017-06-08 10:35:23', 35814, 1054);
INSERT INTO Pessoa (nome) VALUES ('Juliana Pedron');
INSERT INTO Spotted (id_spot, texto, horário, cita) VALUES (35813, 'Juliana Pedron seu olhos lindos e seu sorriso fofo me encantaram, você é deslumbrante menina. Me diz ai, tu namora??', '2017-06-08 05:45:08', 1058);
INSERT INTO Pessoa (nome) VALUES ('Rodrigo Shizuo Yasuda');
INSERT INTO Pessoa (nome) VALUES ('Rebeca Gonçalves');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1059, 35813, 'curtiu');
INSERT INTO Reage(id_pes, id_spot, tipo) VALUES (1060, 35813, 'curtiu');
INSERT INTO Comentario (id_coment, texto, horario, id_spot) VALUES (1, 'Juh Pedron hahahha', '2017-06-08 09:30:21', 35813);
INSERT INTO Pessoa (nome) ('Laion Cesar');
INSERT INTO Spotted (id_spot, texto, horário, cita) VALUES (35812, 'Laion Cesar, sdds de vc, leãozinho', '2017-06-08 05:44:11', 1061);
INSERT INTO Spotted (id_spot, texto, horário) VALUES (35811, '[Ajuda Spotted] Marque seu amigo que estava de xadrez e chapéu rosa no arraia da Feagri .. É pro meu tcc gente.', '2017-06-08 05:44:05');
INSERT INTO Pessoa (nome) VALUES ('Daiane Silva');
INSERT INTO Pessoa (nome) VALUES ('Enrico Oliveira Rocheti');
INSERT INTO Pessoa (nome) VALUES ('Juliana Esper');
INSERT INTO Pessoa (nome) VALUES ('Kaan Oliveira');
INSERT INTO Pessoa (nome) VALUES ('Tercio Vitor');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1062, 35811, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1063, 35811, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1064, 35811, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1065, 35811, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1066, 35811, 'curtiu');
INSERT INTO Pessoa (nome) VALUES ('Charles Carvalho');
INSERT INTO Pessoa (nome) VALUES ('Larissa Fonseca');
INSERT INTO Pessoa (nome) VALUES ('Lucas Vida');
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES(1, 'Kauã Vieira olha elaaaaaa', '2017-06-08 11:18:52', 35811, 1067);
INSERT INTO Comentario (id_coment, texto, horario, id_spot, autor) VALUES(2, 'eeeeepa Kauã Vieira e Lucas Vida', '2017-06-08 11:19:35', 35811, 1065);
INSERT INTO Comentario(id_coment, texto, horario, id_spot, autor) VALUES (3, 'Kauã Vieira', '2017-06-08 10:26:56', 35811, 1068);
INSERT INTO Comentario(id_coment, texto, horario, id_spot, autor) VALUES (4, 'Bruno Caram', '2017-06-08 10:45:36', 35811, 1069);
INSERT INTO Spotted (id_spot, texto, horário) VALUES (35810, 'Cansada desses afetos tão superficiais. Não precisa namorar muito menos casar comigo, apenas gostaria de ser olhada como um ser humano que tem emoções e que não é descartável. Vivemos em uma disputa de egos em q o mais forte é aquele que "pega mais" e se apega menos. Porque tanta negação dos bons sentimentos e da proximidade ao outro?', '2017-06-08 05:44:21');
INSERT INTO Pessoa (nome) VALUES ('Camila Giesz Bortolin');
INSERT INTO Pessoa (nome) VALUES ('João Paulo Rousseff');
INSERT INTO Pessoa (nome) VALUES ('Luane Casagrande');
INSERT INTO Pessoa (nome) VALUES ('Rogerio Mekaro');
INSERT INTO Pessoa (nome) VALUES ('Tharly Lucena');
INSERT INTO Pessoa (nome) VALUES ('Bruna Cristina Cordeiro');
INSERT INTO Pessoa (nome) VALUES ('Thais Bernardes');
INSERT INTO Pessoa (nome) VALUES ('Fernando Dobbert Sanches');
INSERT INTO Pessoa (nome) VALUES ('Jessyca Nobre');
INSERT INTO Pessoa (nome) VALUES ('Giulia Ferreira');
INSERT INTO Pessoa (nome) VALUES ('Caroline Tozzo');
INSERT INTO Pessoa (nome) VALUES ('Livia Assis');
INSERT INTO Pessoa (nome) VALUES ('Rodrigo Appendino');
INSERT INTO Pessoa (nome) VALUES ('Byanca Cristina');
INSERT INTO Pessoa (nome) VALUES ('Mariana Tase');
INSERT INTO Pessoa (nome) VALUES ('Isadora Cappuccelli');
INSERT INTO Pessoa (nome) VALUES ('Ana Luiza Polatto');
INSERT INTO Pessoa (nome) VALUES ('Bárbara Auricchio');
INSERT INTO Pessoa (nome) VALUES ('Ana Beatriz Bartolomei Signorelli');
INSERT INTO Pessoa (nome) VALUES ('Felipe Silva');
INSERT INTO Pessoa (nome) VALUES ('Gabi Polezi');
INSERT INTO Pessoa (nome) VALUES ('Dayana Joicy');
INSERT INTO Pessoa (nome) VALUES ('Bruna Bimbatti');
INSERT INTO Pessoa (nome) VALUES ('Thayná Carvalho');
INSERT INTO Pessoa (nome) VALUES ('Marcos Antônio');
INSERT INTO Pessoa (nome) VALUES ('Camilla Oliveira');
INSERT INTO Pessoa (nome) VALUES ('Julia Maluf');
INSERT INTO Pessoa (nome) VALUES ('Isabella Mattoso');
INSERT INTO Pessoa (nome) VALUES ('Matheus Donatti');
INSERT INTO Pessoa (nome) VALUES ('Bárbara Benevides');
INSERT INTO Pessoa (nome) VALUES ('Leandro Pio de Souza');
INSERT INTO Pessoa (nome) VALUES ('Guilherme Medeiros');
INSERT INTO Pessoa (nome) VALUES ('Gabriel Machado');
INSERT INTO Pessoa (nome) VALUES ('Sofia Carvalho');
INSERT INTO Pessoa (nome) VALUES ('Jaqueline Lopes');
INSERT INTO Pessoa (nome) VALUES ('Vinicius Agnelli Panzetti');
INSERT INTO Pessoa (nome) VALUES ('Juliana Buffo');
INSERT INTO Pessoa (nome) VALUES ('Bruna Kuhl');
INSERT INTO Pessoa (nome) VALUES ('Vinicius Berteli');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1009, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1019, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1030, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1070, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1071, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1072, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1073, 35810, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1074, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1075, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1076, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1077, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1078, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1079, 35810, 'triste');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1080, 35810, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1082, 35810, 'triste');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1083, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1084, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1085, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1086, 35810, 'triste');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1087, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1088, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1089, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1090, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1091, 35810, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1092, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1094, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1095, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1096, 35810, 'triste');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1097, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1098, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1099, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1100, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1101, 35810, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1102, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1103, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1104, 35810, 'triste');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1105, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1106, 35810, 'curtiu');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1107, 35810, 'amei');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1108, 35810, 'triste');
INSERT INTO Reage (id_pes, id_spot, tipo) VALUES (1081, 35810, 'curtiu');
INSERT INTO Descrita (id_pes, id_tag) VALUES (1028, 13);
insert into Tag (nome, quantidade) values ('morbi', 26);
insert into Tag (nome, quantidade) values ('magnis', 22);
insert into Tag (nome, quantidade) values ('tincidunt', 50);
insert into Tag (nome, quantidade) values ('cursus', 7);
insert into Tag (nome, quantidade) values ('placerat', 4);
insert into Tag (nome, quantidade) values ('cubilia', 2);
insert into Tag (nome, quantidade) values ('habitasse', 18);
insert into Tag (nome, quantidade) values ('gravida', 32);
insert into Tag (nome, quantidade) values ('sagittis', 18);
insert into Tag (nome, quantidade) values ('maecenas', 10);
insert into Tag (nome, quantidade) values ('ultrices', 29);
insert into Tag (nome, quantidade) values ('duis', 1);
insert into Tag (nome, quantidade) values ('luctus', 48);
insert into Tag (nome, quantidade) values ('in', 3);
insert into Tag (nome, quantidade) values ('ultrices', 27);
insert into Tag (nome, quantidade) values ('vivamus', 49);
insert into Tag (nome, quantidade) values ('tortor', 56);
insert into Tag (nome, quantidade) values ('aliquet', 45);
insert into Tag (nome, quantidade) values ('libero', 55);
insert into Tag (nome, quantidade) values ('dapibus', 53);
insert into Tag (nome, quantidade) values ('tincidunt', 30);
insert into Tag (nome, quantidade) values ('hac', 7);
insert into Tag (nome, quantidade) values ('nullam', 43);
insert into Tag (nome, quantidade) values ('pede', 20);
insert into Tag (nome, quantidade) values ('convallis', 2);
insert into Tag (nome, quantidade) values ('sed', 2);
insert into Tag (nome, quantidade) values ('cubilia', 46);
insert into Tag (nome, quantidade) values ('est', 12);
insert into Tag (nome, quantidade) values ('nunc', 56);
insert into Tag (nome, quantidade) values ('justo', 8);
insert into Tag (nome, quantidade) values ('et', 38);
insert into Tag (nome, quantidade) values ('sed', 53);
insert into Tag (nome, quantidade) values ('primis', 1);
insert into Tag (nome, quantidade) values ('interdum', 55);
insert into Tag (nome, quantidade) values ('odio', 26);
insert into Tag (nome, quantidade) values ('augue', 25);
insert into Tag (nome, quantidade) values ('tellus', 60);
insert into Tag (nome, quantidade) values ('turpis', 34);
insert into Tag (nome, quantidade) values ('in', 9);
insert into Tag (nome, quantidade) values ('aenean', 56);
insert into Tag (nome, quantidade) values ('laoreet', 1);
insert into Tag (nome, quantidade) values ('non', 44);
insert into Tag (nome, quantidade) values ('amet', 50);
insert into Tag (nome, quantidade) values ('est', 56);
insert into Tag (nome, quantidade) values ('eget', 23);
insert into Tag (nome, quantidade) values ('dolor', 53);
insert into Tag (nome, quantidade) values ('condimentum', 5);
insert into Tag (nome, quantidade) values ('viverra', 43);
insert into Tag (nome, quantidade) values ('luctus', 25);
insert into Tag (nome, quantidade) values ('dapibus', 37);
insert into Tag (nome, quantidade) values ('malesuada', 31);
insert into Tag (nome, quantidade) values ('orci', 40);
insert into Tag (nome, quantidade) values ('magna', 23);
insert into Tag (nome, quantidade) values ('aliquam', 60);
insert into Tag (nome, quantidade) values ('vitae', 9);
insert into Tag (nome, quantidade) values ('sociis', 3);
insert into Tag (nome, quantidade) values ('leo', 53);
insert into Tag (nome, quantidade) values ('odio', 45);
insert into Tag (nome, quantidade) values ('tristique', 43);
insert into Tag (nome, quantidade) values ('velit', 20);
insert into Tag (nome, quantidade) values ('amet', 52);
insert into Tag (nome, quantidade) values ('sit', 58);
insert into Tag (nome, quantidade) values ('odio', 60);
insert into Tag (nome, quantidade) values ('vel', 29);
insert into Tag (nome, quantidade) values ('suspendisse', 50);
insert into Tag (nome, quantidade) values ('id', 38);
insert into Tag (nome, quantidade) values ('cras', 56);
insert into Tag (nome, quantidade) values ('dui', 35);
insert into Tag (nome, quantidade) values ('dapibus', 60);
insert into Tag (nome, quantidade) values ('quis', 32);
insert into Tag (nome, quantidade) values ('enim', 45);
insert into Tag (nome, quantidade) values ('magna', 24);
insert into Tag (nome, quantidade) values ('odio', 58);
insert into Tag (nome, quantidade) values ('sollicitudin', 37);
insert into Tag (nome, quantidade) values ('blandit', 35);
insert into Tag (nome, quantidade) values ('cubilia', 50);
insert into Tag (nome, quantidade) values ('pede', 28);
insert into Tag (nome, quantidade) values ('mi', 57);
insert into Tag (nome, quantidade) values ('pede', 17);
insert into Tag (nome, quantidade) values ('tellus', 36);
insert into Tag (nome, quantidade) values ('amet', 31);
insert into Tag (nome, quantidade) values ('nulla', 51);
insert into Tag (nome, quantidade) values ('eros', 28);
insert into Tag (nome, quantidade) values ('consequat', 57);
insert into Tag (nome, quantidade) values ('vestibulum', 45);
insert into Tag (nome, quantidade) values ('ridiculus', 15);
insert into Tag (nome, quantidade) values ('duis', 53);
insert into Tag (nome, quantidade) values ('praesent', 2);
insert into Tag (nome, quantidade) values ('vulputate', 57);
insert into Tag (nome, quantidade) values ('diam', 24);
insert into Tag (nome, quantidade) values ('amet', 18);
insert into Tag (nome, quantidade) values ('tincidunt', 16);
insert into Tag (nome, quantidade) values ('pellentesque', 13);
insert into Tag (nome, quantidade) values ('lacinia', 41);
insert into Tag (nome, quantidade) values ('integer', 36);
insert into Tag (nome, quantidade) values ('nulla', 31);
insert into Tag (nome, quantidade) values ('justo', 53);
insert into Tag (nome, quantidade) values ('et', 37);
insert into Tag (nome, quantidade) values ('odio', 53);
insert into Tag (nome, quantidade) values ('interdum', 12);
insert into Tag (nome, quantidade) values ('urna', 17);
insert into Tag (nome, quantidade) values ('nunc', 32);
insert into Tag (nome, quantidade) values ('in', 46);
insert into Tag (nome, quantidade) values ('a', 50);
insert into Tag (nome, quantidade) values ('bibendum', 35);
insert into Tag (nome, quantidade) values ('nisl', 39);
insert into Tag (nome, quantidade) values ('pretium', 44);
insert into Tag (nome, quantidade) values ('mus', 47);
insert into Tag (nome, quantidade) values ('fusce', 10);
insert into Tag (nome, quantidade) values ('ullamcorper', 58);
insert into Tag (nome, quantidade) values ('lacus', 59);
insert into Tag (nome, quantidade) values ('at', 48);
insert into Tag (nome, quantidade) values ('non', 2);
insert into Tag (nome, quantidade) values ('in', 5);
insert into Tag (nome, quantidade) values ('non', 23);
insert into Tag (nome, quantidade) values ('lacinia', 6);
insert into Tag (nome, quantidade) values ('nec', 27);
insert into Tag (nome, quantidade) values ('ultrices', 20);
insert into Tag (nome, quantidade) values ('ridiculus', 37);
insert into Tag (nome, quantidade) values ('orci', 6);
insert into Tag (nome, quantidade) values ('habitasse', 59);
insert into Tag (nome, quantidade) values ('ante', 25);
insert into Tag (nome, quantidade) values ('interdum', 46);
insert into Tag (nome, quantidade) values ('id', 59);
insert into Tag (nome, quantidade) values ('potenti', 41);
insert into Tag (nome, quantidade) values ('volutpat', 51);
insert into Tag (nome, quantidade) values ('at', 32);
insert into Tag (nome, quantidade) values ('et', 41);
insert into Tag (nome, quantidade) values ('sed', 2);
insert into Tag (nome, quantidade) values ('sem', 50);
insert into Tag (nome, quantidade) values ('eros', 2);
insert into Tag (nome, quantidade) values ('aliquet', 55);
insert into Tag (nome, quantidade) values ('dictumst', 51);
insert into Tag (nome, quantidade) values ('tempus', 12);
insert into Tag (nome, quantidade) values ('erat', 26);
insert into Tag (nome, quantidade) values ('venenatis', 24);
insert into Tag (nome, quantidade) values ('ac', 32);
insert into Tag (nome, quantidade) values ('at', 7);
insert into Tag (nome, quantidade) values ('turpis', 17);
insert into Tag (nome, quantidade) values ('interdum', 42);
insert into Tag (nome, quantidade) values ('leo', 30);
insert into Tag (nome, quantidade) values ('hendrerit', 8);
insert into Tag (nome, quantidade) values ('et', 36);
insert into Tag (nome, quantidade) values ('maecenas', 48);
insert into Tag (nome, quantidade) values ('vestibulum', 4);
insert into Tag (nome, quantidade) values ('consequat', 28);
insert into Tag (nome, quantidade) values ('vestibulum', 47);
insert into Tag (nome, quantidade) values ('nibh', 20);
insert into Tag (nome, quantidade) values ('non', 48);
insert into Tag (nome, quantidade) values ('et', 34);
insert into Tag (nome, quantidade) values ('nisi', 3);
insert into Tag (nome, quantidade) values ('justo', 50);
insert into Tag (nome, quantidade) values ('sociis', 17);
insert into Tag (nome, quantidade) values ('at', 49);
insert into Tag (nome, quantidade) values ('convallis', 11);
insert into Tag (nome, quantidade) values ('quisque', 15);
insert into Tag (nome, quantidade) values ('vitae', 33);
insert into Tag (nome, quantidade) values ('viverra', 51);
insert into Tag (nome, quantidade) values ('elementum', 21);
insert into Tag (nome, quantidade) values ('neque', 33);
insert into Tag (nome, quantidade) values ('tristique', 42);
insert into Tag (nome, quantidade) values ('in', 29);
insert into Tag (nome, quantidade) values ('posuere', 46);
insert into Tag (nome, quantidade) values ('nulla', 1);
insert into Tag (nome, quantidade) values ('tristique', 56);
insert into Tag (nome, quantidade) values ('at', 5);
insert into Tag (nome, quantidade) values ('ligula', 4);
insert into Tag (nome, quantidade) values ('euismod', 33);
insert into Tag (nome, quantidade) values ('quam', 53);
insert into Tag (nome, quantidade) values ('eleifend', 41);
insert into Tag (nome, quantidade) values ('eget', 43);
insert into Tag (nome, quantidade) values ('orci', 29);
insert into Tag (nome, quantidade) values ('odio', 1);
insert into Tag (nome, quantidade) values ('cum', 49);
insert into Tag (nome, quantidade) values ('lorem', 23);
insert into Tag (nome, quantidade) values ('ipsum', 11);
insert into Tag (nome, quantidade) values ('diam', 2);
insert into Tag (nome, quantidade) values ('pede', 20);
insert into Tag (nome, quantidade) values ('nulla', 18);
insert into Tag (nome, quantidade) values ('donec', 24);
insert into Tag (nome, quantidade) values ('vel', 43);
insert into Tag (nome, quantidade) values ('erat', 59);
insert into Tag (nome, quantidade) values ('eget', 52);
insert into Tag (nome, quantidade) values ('aliquam', 37);
insert into Tag (nome, quantidade) values ('lorem', 57);
insert into Tag (nome, quantidade) values ('nulla', 56);
insert into Tag (nome, quantidade) values ('eu', 1);
insert into Tag (nome, quantidade) values ('mattis', 1);
insert into Tag (nome, quantidade) values ('sed', 24);
insert into Tag (nome, quantidade) values ('blandit', 45);
insert into Tag (nome, quantidade) values ('lacus', 34);
insert into Tag (nome, quantidade) values ('purus', 19);
insert into Tag (nome, quantidade) values ('lacus', 46);
insert into Tag (nome, quantidade) values ('nibh', 12);
insert into Tag (nome, quantidade) values ('in', 25);
insert into Tag (nome, quantidade) values ('consequat', 20);
insert into Tag (nome, quantidade) values ('ultrices', 45);
insert into Tag (nome, quantidade) values ('primis', 11);
insert into Tag (nome, quantidade) values ('nulla', 31);
insert into Tag (nome, quantidade) values ('eget', 9);
insert into Tag (nome, quantidade) values ('dui', 31);
insert into Tag (nome, quantidade) values ('aliquet', 29);
insert into Tag (nome, quantidade) values ('cubilia', 2);
insert into Tag (nome, quantidade) values ('duis', 53);
insert into Tag (nome, quantidade) values ('tristique', 15);
insert into Tag (nome, quantidade) values ('mauris', 36);
insert into Tag (nome, quantidade) values ('amet', 43);
insert into Tag (nome, quantidade) values ('tempus', 12);
insert into Tag (nome, quantidade) values ('turpis', 34);
insert into Tag (nome, quantidade) values ('vulputate', 44);
insert into Tag (nome, quantidade) values ('vel', 17);
insert into Tag (nome, quantidade) values ('ornare', 49);
insert into Tag (nome, quantidade) values ('maecenas', 11);
insert into Tag (nome, quantidade) values ('sit', 57);
insert into Tag (nome, quantidade) values ('sapien', 1);
insert into Tag (nome, quantidade) values ('lacus', 41);
insert into Tag (nome, quantidade) values ('elit', 31);
insert into Tag (nome, quantidade) values ('in', 4);
insert into Tag (nome, quantidade) values ('turpis', 40);
insert into Tag (nome, quantidade) values ('eget', 42);
insert into Tag (nome, quantidade) values ('ipsum', 56);
insert into Tag (nome, quantidade) values ('nisi', 10);
insert into Tag (nome, quantidade) values ('consequat', 3);
insert into Tag (nome, quantidade) values ('ultrices', 46);
insert into Tag (nome, quantidade) values ('luctus', 55);
insert into Tag (nome, quantidade) values ('nonummy', 31);
insert into Tag (nome, quantidade) values ('erat', 26);
insert into Tag (nome, quantidade) values ('mattis', 25);
insert into Tag (nome, quantidade) values ('consequat', 6);
insert into Tag (nome, quantidade) values ('consequat', 3);
insert into Tag (nome, quantidade) values ('praesent', 5);
insert into Tag (nome, quantidade) values ('justo', 44);
insert into Tag (nome, quantidade) values ('eros', 27);
insert into Tag (nome, quantidade) values ('in', 29);
insert into Tag (nome, quantidade) values ('nascetur', 31);
insert into Tag (nome, quantidade) values ('porttitor', 26);
insert into Tag (nome, quantidade) values ('non', 34);
insert into Tag (nome, quantidade) values ('massa', 2);
insert into Tag (nome, quantidade) values ('nulla', 46);
insert into Tag (nome, quantidade) values ('etiam', 25);
insert into Tag (nome, quantidade) values ('cras', 5);
insert into Tag (nome, quantidade) values ('augue', 10);
insert into Tag (nome, quantidade) values ('penatibus', 41);
insert into Tag (nome, quantidade) values ('augue', 26);
insert into Tag (nome, quantidade) values ('consequat', 29);
insert into Tag (nome, quantidade) values ('venenatis', 34);
insert into Tag (nome, quantidade) values ('in', 13);
insert into Tag (nome, quantidade) values ('mattis', 47);
insert into Tag (nome, quantidade) values ('ac', 57);
insert into Tag (nome, quantidade) values ('duis', 8);
insert into Tag (nome, quantidade) values ('duis', 33);
insert into Tag (nome, quantidade) values ('ac', 38);
insert into Tag (nome, quantidade) values ('sed', 9);
insert into Tag (nome, quantidade) values ('rhoncus', 31);
insert into Tag (nome, quantidade) values ('nulla', 32);
insert into Tag (nome, quantidade) values ('luctus', 1);
insert into Tag (nome, quantidade) values ('at', 42);
insert into Tag (nome, quantidade) values ('interdum', 3);
insert into Tag (nome, quantidade) values ('non', 16);
insert into Tag (nome, quantidade) values ('est', 32);
insert into Tag (nome, quantidade) values ('ultrices', 50);
insert into Tag (nome, quantidade) values ('vitae', 4);
insert into Tag (nome, quantidade) values ('integer', 6);
insert into Tag (nome, quantidade) values ('blandit', 28);
insert into Tag (nome, quantidade) values ('sit', 55);
insert into Tag (nome, quantidade) values ('in', 15);
insert into Tag (nome, quantidade) values ('sapien', 4);
insert into Tag (nome, quantidade) values ('justo', 19);
insert into Tag (nome, quantidade) values ('eget', 10);
insert into Tag (nome, quantidade) values ('dignissim', 30);
insert into Tag (nome, quantidade) values ('fusce', 9);
insert into Tag (nome, quantidade) values ('posuere', 60);
insert into Tag (nome, quantidade) values ('ipsum', 32);
insert into Tag (nome, quantidade) values ('id', 8);
insert into Tag (nome, quantidade) values ('arcu', 21);
insert into Tag (nome, quantidade) values ('lobortis', 9);
insert into Tag (nome, quantidade) values ('tortor', 42);
insert into Tag (nome, quantidade) values ('tincidunt', 17);
insert into Tag (nome, quantidade) values ('consequat', 59);
insert into Tag (nome, quantidade) values ('erat', 3);
insert into Tag (nome, quantidade) values ('potenti', 14);
insert into Tag (nome, quantidade) values ('hac', 17);
insert into Tag (nome, quantidade) values ('ligula', 59);
insert into Tag (nome, quantidade) values ('eleifend', 23);
insert into Tag (nome, quantidade) values ('in', 8);
insert into Tag (nome, quantidade) values ('odio', 26);
insert into Tag (nome, quantidade) values ('arcu', 19);
insert into Tag (nome, quantidade) values ('posuere', 3);
insert into Tag (nome, quantidade) values ('phasellus', 12);
insert into Tag (nome, quantidade) values ('eget', 6);
insert into Tag (nome, quantidade) values ('posuere', 3);
insert into Tag (nome, quantidade) values ('id', 60);
insert into Tag (nome, quantidade) values ('sed', 18);
insert into Tag (nome, quantidade) values ('libero', 23);
insert into Tag (nome, quantidade) values ('a', 54);
insert into Tag (nome, quantidade) values ('sapien', 39);
insert into Tag (nome, quantidade) values ('nulla', 11);
insert into Tag (nome, quantidade) values ('leo', 8);
insert into Tag (nome, quantidade) values ('vivamus', 33);
insert into Tag (nome, quantidade) values ('nulla', 48);
insert into Fenotipo (id_tag, categoria) values (147, 'cor dos olhos');
insert into Fenotipo (id_tag, categoria) values (239, 'cor de pele');
insert into Fenotipo (id_tag, categoria) values (130, 'tamanho do pé');
insert into Fenotipo (id_tag, categoria) values (14, 'número de narinas');
insert into Fenotipo (id_tag, categoria) values (11, 'tipo de cabelo');
insert into Fenotipo (id_tag, categoria) values (255, 'tamanho do cabelo');
insert into Fenotipo (id_tag, categoria) values (45, 'altura');
insert into Fenotipo (id_tag, categoria) values (88, 'largura');
insert into Fenotipo (id_tag, categoria) values (159, 'comprimento');
insert into Fenotipo (id_tag, categoria) values (26, 'QI');
insert into Fenotipo (id_tag, categoria) values (153, 'CR');
insert into Fenotipo (id_tag, categoria) values (279, 'Conta Bancária');
insert into Fenotipo (id_tag, categoria) values (282, 'Oleosidade');
insert into Fenotipo (id_tag, categoria) values (249, 'Barba');
insert into Fenotipo (id_tag, categoria) values (170, 'Tipo Físico');
insert into Fenotipo (id_tag, categoria) values (198, 'Bumbum');
insert into Fenotipo (id_tag, categoria) values (200, 'Número de dentes');
insert into Fenotipo (id_tag, categoria) values (53, 'Cicatriz');
insert into Fenotipo (id_tag, categoria) values (80, 'Taguagem');
insert into Fenotipo (id_tag, categoria) values (22, 'Piercing');
insert into Fenotipo (id_tag, categoria) values (157, 'Ferimentos');
insert into Fenotipo (id_tag, categoria) values (71, 'Adesivos');
insert into Fenotipo (id_tag, categoria) values (8, 'Bigode');
insert into Fenotipo (id_tag, categoria) values (196, 'Lóbulo colado');
insert into Fenotipo (id_tag, categoria) values (182, 'Bico de Viúva');
insert into Fenotipo (id_tag, categoria) values (165, 'Maxilar');
insert into Fenotipo (id_tag, categoria) values (294, 'Capacete');
insert into Fenotipo (id_tag, categoria) values (228, 'Chinelo');
insert into Fenotipo (id_tag, categoria) values (226, 'Brinco');
insert into Fenotipo (id_tag, categoria) values (41, 'Escamas');
insert into Contem (id_spot, id_tag) values (167, 91);
insert into Contem (id_spot, id_tag) values (99, 47);
insert into Contem (id_spot, id_tag) values (233, 245);
insert into Contem (id_spot, id_tag) values (92, 282);
insert into Contem (id_spot, id_tag) values (120, 225);
insert into Contem (id_spot, id_tag) values (247, 50);
insert into Contem (id_spot, id_tag) values (151, 72);
insert into Contem (id_spot, id_tag) values (144, 92);
insert into Contem (id_spot, id_tag) values (76, 169);
insert into Contem (id_spot, id_tag) values (88, 253);
insert into Contem (id_spot, id_tag) values (150, 124);
insert into Contem (id_spot, id_tag) values (247, 59);
insert into Contem (id_spot, id_tag) values (141, 236);
insert into Contem (id_spot, id_tag) values (200, 96);
insert into Contem (id_spot, id_tag) values (49, 83);
insert into Contem (id_spot, id_tag) values (48, 239);
insert into Contem (id_spot, id_tag) values (79, 181);
insert into Contem (id_spot, id_tag) values (179, 80);
insert into Contem (id_spot, id_tag) values (223, 210);
insert into Contem (id_spot, id_tag) values (248, 145);
insert into Contem (id_spot, id_tag) values (251, 257);
insert into Contem (id_spot, id_tag) values (250, 199);
insert into Contem (id_spot, id_tag) values (241, 239);
insert into Contem (id_spot, id_tag) values (186, 307);
insert into Contem (id_spot, id_tag) values (15, 298);
insert into Contem (id_spot, id_tag) values (15, 45);
insert into Contem (id_spot, id_tag) values (19, 190);
insert into Contem (id_spot, id_tag) values (108, 13);
insert into Contem (id_spot, id_tag) values (36, 75);
insert into Contem (id_spot, id_tag) values (242, 126);
insert into Contem (id_spot, id_tag) values (101, 35);
insert into Contem (id_spot, id_tag) values (105, 91);
insert into Contem (id_spot, id_tag) values (96, 18);
insert into Contem (id_spot, id_tag) values (250, 154);
insert into Contem (id_spot, id_tag) values (142, 170);
insert into Contem (id_spot, id_tag) values (143, 99);
insert into Contem (id_spot, id_tag) values (90, 161);
insert into Contem (id_spot, id_tag) values (92, 121);
insert into Contem (id_spot, id_tag) values (213, 12);
insert into Contem (id_spot, id_tag) values (130, 164);
insert into Contem (id_spot, id_tag) values (111, 264);
insert into Contem (id_spot, id_tag) values (57, 308);
insert into Contem (id_spot, id_tag) values (216, 204);
insert into Contem (id_spot, id_tag) values (59, 52);
insert into Contem (id_spot, id_tag) values (66, 206);
insert into Contem (id_spot, id_tag) values (182, 237);
insert into Contem (id_spot, id_tag) values (116, 233);
insert into Contem (id_spot, id_tag) values (237, 70);
insert into Contem (id_spot, id_tag) values (209, 179);
insert into Contem (id_spot, id_tag) values (217, 196);
insert into Contem (id_spot, id_tag) values (146, 32);
insert into Contem (id_spot, id_tag) values (57, 61);
insert into Contem (id_spot, id_tag) values (130, 270);
insert into Contem (id_spot, id_tag) values (162, 24);
insert into Contem (id_spot, id_tag) values (104, 166);
insert into Contem (id_spot, id_tag) values (121, 40);
insert into Contem (id_spot, id_tag) values (204, 113);
insert into Contem (id_spot, id_tag) values (209, 20);
insert into Contem (id_spot, id_tag) values (175, 226);
insert into Contem (id_spot, id_tag) values (207, 128);
insert into Contem (id_spot, id_tag) values (243, 43);
insert into Contem (id_spot, id_tag) values (166, 21);
insert into Contem (id_spot, id_tag) values (38, 118);
insert into Contem (id_spot, id_tag) values (36, 41);
insert into Contem (id_spot, id_tag) values (226, 51);
insert into Contem (id_spot, id_tag) values (228, 123);
insert into Contem (id_spot, id_tag) values (198, 291);
insert into Contem (id_spot, id_tag) values (197, 152);
insert into Contem (id_spot, id_tag) values (216, 14);
insert into Contem (id_spot, id_tag) values (231, 24);
insert into Contem (id_spot, id_tag) values (29, 148);
insert into Contem (id_spot, id_tag) values (19, 275);
insert into Contem (id_spot, id_tag) values (122, 221);
insert into Contem (id_spot, id_tag) values (196, 231);
insert into Contem (id_spot, id_tag) values (155, 230);
insert into Contem (id_spot, id_tag) values (17, 217);
insert into Contem (id_spot, id_tag) values (74, 99);
insert into Contem (id_spot, id_tag) values (185, 286);
insert into Contem (id_spot, id_tag) values (224, 207);
insert into Contem (id_spot, id_tag) values (121, 32);
insert into Contem (id_spot, id_tag) values (86, 120);
insert into Contem (id_spot, id_tag) values (179, 140);
insert into Contem (id_spot, id_tag) values (100, 267);
insert into Contem (id_spot, id_tag) values (122, 277);
insert into Contem (id_spot, id_tag) values (261, 161);
insert into Contem (id_spot, id_tag) values (39, 16);
insert into Contem (id_spot, id_tag) values (243, 132);
insert into Contem (id_spot, id_tag) values (252, 58);
insert into Contem (id_spot, id_tag) values (28, 247);
insert into Contem (id_spot, id_tag) values (256, 120);
insert into Contem (id_spot, id_tag) values (155, 202);
insert into Contem (id_spot, id_tag) values (194, 66);
insert into Contem (id_spot, id_tag) values (198, 251);
insert into Contem (id_spot, id_tag) values (220, 186);
insert into Contem (id_spot, id_tag) values (116, 276);
insert into Contem (id_spot, id_tag) values (12, 242);
insert into Contem (id_spot, id_tag) values (181, 42);
insert into Contem (id_spot, id_tag) values (49, 37);
insert into Contem (id_spot, id_tag) values (80, 285);
insert into Contem (id_spot, id_tag) values (71, 229);
insert into Contem (id_spot, id_tag) values (222, 204);
insert into Contem (id_spot, id_tag) values (86, 144);
insert into Contem (id_spot, id_tag) values (153, 131);
insert into Contem (id_spot, id_tag) values (48, 298);
insert into Contem (id_spot, id_tag) values (235, 6);
insert into Contem (id_spot, id_tag) values (112, 252);
insert into Contem (id_spot, id_tag) values (48, 213);
insert into Contem (id_spot, id_tag) values (247, 126);
insert into Contem (id_spot, id_tag) values (63, 133);
insert into Contem (id_spot, id_tag) values (251, 189);
insert into Contem (id_spot, id_tag) values (65, 195);
insert into Contem (id_spot, id_tag) values (261, 284);
insert into Contem (id_spot, id_tag) values (151, 30);
insert into Contem (id_spot, id_tag) values (228, 189);
insert into Contem (id_spot, id_tag) values (135, 168);
insert into Contem (id_spot, id_tag) values (103, 176);
insert into Contem (id_spot, id_tag) values (199, 156);
insert into Contem (id_spot, id_tag) values (144, 145);
insert into Contem (id_spot, id_tag) values (76, 63);
insert into Contem (id_spot, id_tag) values (156, 197);
insert into Contem (id_spot, id_tag) values (250, 5);
insert into Contem (id_spot, id_tag) values (47, 240);
insert into Contem (id_spot, id_tag) values (46, 103);
insert into Contem (id_spot, id_tag) values (37, 250);
insert into Contem (id_spot, id_tag) values (190, 129);
insert into Contem (id_spot, id_tag) values (217, 154);
insert into Contem (id_spot, id_tag) values (182, 7);
insert into Contem (id_spot, id_tag) values (154, 295);
insert into Contem (id_spot, id_tag) values (126, 286);
insert into Contem (id_spot, id_tag) values (236, 136);
insert into Contem (id_spot, id_tag) values (47, 119);
insert into Contem (id_spot, id_tag) values (184, 15);
insert into Contem (id_spot, id_tag) values (210, 76);
insert into Contem (id_spot, id_tag) values (196, 19);
insert into Contem (id_spot, id_tag) values (124, 201);
insert into Contem (id_spot, id_tag) values (230, 277);
insert into Contem (id_spot, id_tag) values (90, 48);
insert into Contem (id_spot, id_tag) values (107, 137);
insert into Contem (id_spot, id_tag) values (100, 140);
insert into Contem (id_spot, id_tag) values (167, 43);
insert into Contem (id_spot, id_tag) values (249, 64);
insert into Contem (id_spot, id_tag) values (213, 234);
insert into Contem (id_spot, id_tag) values (87, 258);
insert into Contem (id_spot, id_tag) values (191, 198);
insert into Contem (id_spot, id_tag) values (243, 130);
insert into Contem (id_spot, id_tag) values (52, 206);
insert into Contem (id_spot, id_tag) values (94, 259);
insert into Contem (id_spot, id_tag) values (59, 178);
insert into Contem (id_spot, id_tag) values (63, 219);
insert into Contem (id_spot, id_tag) values (17, 283);
insert into Contem (id_spot, id_tag) values (196, 214);
insert into Contem (id_spot, id_tag) values (29, 4);
insert into Contem (id_spot, id_tag) values (211, 247);
insert into Contem (id_spot, id_tag) values (247, 21);
insert into Contem (id_spot, id_tag) values (94, 29);
insert into Contem (id_spot, id_tag) values (203, 232);
insert into Contem (id_spot, id_tag) values (237, 80);
insert into Contem (id_spot, id_tag) values (81, 21);
insert into Contem (id_spot, id_tag) values (186, 270);
insert into Contem (id_spot, id_tag) values (114, 311);
insert into Contem (id_spot, id_tag) values (207, 289);
insert into Contem (id_spot, id_tag) values (38, 53);
insert into Contem (id_spot, id_tag) values (25, 110);
insert into Contem (id_spot, id_tag) values (22, 244);
insert into Contem (id_spot, id_tag) values (32, 203);
insert into Contem (id_spot, id_tag) values (17, 243);
insert into Contem (id_spot, id_tag) values (165, 145);
insert into Contem (id_spot, id_tag) values (206, 18);
insert into Contem (id_spot, id_tag) values (61, 13);
insert into Contem (id_spot, id_tag) values (169, 101);
insert into Contem (id_spot, id_tag) values (188, 218);
insert into Contem (id_spot, id_tag) values (137, 102);
insert into Contem (id_spot, id_tag) values (145, 268);
insert into Contem (id_spot, id_tag) values (259, 214);
insert into Contem (id_spot, id_tag) values (221, 81);
insert into Contem (id_spot, id_tag) values (44, 7);
insert into Contem (id_spot, id_tag) values (105, 279);
insert into Contem (id_spot, id_tag) values (72, 140);
insert into Contem (id_spot, id_tag) values (52, 252);
insert into Contem (id_spot, id_tag) values (112, 98);
insert into Contem (id_spot, id_tag) values (24, 125);
insert into Contem (id_spot, id_tag) values (124, 197);
insert into Contem (id_spot, id_tag) values (105, 244);
insert into Contem (id_spot, id_tag) values (159, 288);
insert into Contem (id_spot, id_tag) values (162, 57);
insert into Contem (id_spot, id_tag) values (57, 130);
insert into Contem (id_spot, id_tag) values (120, 46);
insert into Contem (id_spot, id_tag) values (188, 183);
insert into Contem (id_spot, id_tag) values (196, 30);
insert into Contem (id_spot, id_tag) values (46, 123);
insert into Contem (id_spot, id_tag) values (203, 277);
insert into Contem (id_spot, id_tag) values (68, 231);
insert into Contem (id_spot, id_tag) values (180, 33);
insert into Contem (id_spot, id_tag) values (122, 205);
insert into Contem (id_spot, id_tag) values (102, 48);
insert into Contem (id_spot, id_tag) values (199, 103);
insert into Contem (id_spot, id_tag) values (66, 140);
insert into Contem (id_spot, id_tag) values (102, 199);
insert into Contem (id_spot, id_tag) values (80, 78);
insert into Contem (id_spot, id_tag) values (188, 168);
insert into Contem (id_spot, id_tag) values (81, 66);
insert into Contem (id_spot, id_tag) values (246, 104);
insert into Contem (id_spot, id_tag) values (109, 8);
insert into Contem (id_spot, id_tag) values (149, 233);
insert into Contem (id_spot, id_tag) values (16, 38);
insert into Contem (id_spot, id_tag) values (104, 258);
insert into Contem (id_spot, id_tag) values (238, 58);
insert into Contem (id_spot, id_tag) values (112, 254);
insert into Contem (id_spot, id_tag) values (64, 243);
insert into Contem (id_spot, id_tag) values (155, 303);
insert into Contem (id_spot, id_tag) values (137, 54);
insert into Contem (id_spot, id_tag) values (70, 248);
insert into Contem (id_spot, id_tag) values (249, 243);
insert into Contem (id_spot, id_tag) values (21, 189);
insert into Contem (id_spot, id_tag) values (112, 34);
insert into Contem (id_spot, id_tag) values (148, 25);
insert into Contem (id_spot, id_tag) values (182, 143);
insert into Contem (id_spot, id_tag) values (73, 125);
insert into Contem (id_spot, id_tag) values (19, 144);
insert into Contem (id_spot, id_tag) values (20, 62);
insert into Contem (id_spot, id_tag) values (160, 62);
insert into Contem (id_spot, id_tag) values (89, 27);
insert into Contem (id_spot, id_tag) values (181, 308);
insert into Contem (id_spot, id_tag) values (223, 157);
insert into Contem (id_spot, id_tag) values (80, 172);
insert into Contem (id_spot, id_tag) values (261, 169);
insert into Contem (id_spot, id_tag) values (220, 246);
insert into Contem (id_spot, id_tag) values (253, 164);
insert into Contem (id_spot, id_tag) values (227, 166);
insert into Contem (id_spot, id_tag) values (174, 207);
insert into Contem (id_spot, id_tag) values (55, 77);
insert into Contem (id_spot, id_tag) values (11, 293);
insert into Contem (id_spot, id_tag) values (16, 152);
insert into Contem (id_spot, id_tag) values (31, 276);
insert into Contem (id_spot, id_tag) values (118, 98);
insert into Contem (id_spot, id_tag) values (134, 311);
insert into Contem (id_spot, id_tag) values (202, 261);
insert into Contem (id_spot, id_tag) values (61, 65);
insert into Contem (id_spot, id_tag) values (84, 175);
insert into Contem (id_spot, id_tag) values (214, 272);
insert into Contem (id_spot, id_tag) values (170, 50);
insert into Contem (id_spot, id_tag) values (226, 44);
insert into Contem (id_spot, id_tag) values (221, 50);
insert into Contem (id_spot, id_tag) values (221, 225);
insert into Contem (id_spot, id_tag) values (113, 153);
insert into Contem (id_spot, id_tag) values (167, 175);
insert into Contem (id_spot, id_tag) values (52, 197);
insert into Contem (id_spot, id_tag) values (98, 158);
insert into Contem (id_spot, id_tag) values (212, 234);
insert into Contem (id_spot, id_tag) values (246, 56);
insert into Contem (id_spot, id_tag) values (250, 189);
insert into Contem (id_spot, id_tag) values (173, 55);
insert into Contem (id_spot, id_tag) values (12, 184);
insert into Contem (id_spot, id_tag) values (175, 86);
insert into Contem (id_spot, id_tag) values (176, 141);
insert into Contem (id_spot, id_tag) values (61, 203);
insert into Contem (id_spot, id_tag) values (228, 153);
insert into Contem (id_spot, id_tag) values (145, 244);
insert into Contem (id_spot, id_tag) values (141, 99);
insert into Contem (id_spot, id_tag) values (110, 234);
insert into Contem (id_spot, id_tag) values (197, 47);
insert into Contem (id_spot, id_tag) values (215, 54);
insert into Contem (id_spot, id_tag) values (142, 105);
insert into Contem (id_spot, id_tag) values (258, 193);
insert into Contem (id_spot, id_tag) values (111, 233);
insert into Contem (id_spot, id_tag) values (122, 187);
insert into Contem (id_spot, id_tag) values (220, 53);
insert into Contem (id_spot, id_tag) values (125, 99);
insert into Contem (id_spot, id_tag) values (209, 46);
insert into Contem (id_spot, id_tag) values (50, 278);
insert into Contem (id_spot, id_tag) values (121, 242);
insert into Contem (id_spot, id_tag) values (248, 204);
insert into Contem (id_spot, id_tag) values (169, 102);
insert into Contem (id_spot, id_tag) values (223, 31);
insert into Contem (id_spot, id_tag) values (147, 67);
insert into Contem (id_spot, id_tag) values (41, 88);
insert into Contem (id_spot, id_tag) values (114, 303);
insert into Contem (id_spot, id_tag) values (27, 194);
insert into Contem (id_spot, id_tag) values (33, 244);
insert into Contem (id_spot, id_tag) values (109, 150);
insert into Contem (id_spot, id_tag) values (31, 202);
insert into Contem (id_spot, id_tag) values (29, 265);
insert into Contem (id_spot, id_tag) values (197, 224);
insert into Contem (id_spot, id_tag) values (96, 260);
insert into Contem (id_spot, id_tag) values (260, 211);
insert into Contem (id_spot, id_tag) values (54, 213);
insert into Contem (id_spot, id_tag) values (164, 143);
insert into Contem (id_spot, id_tag) values (22, 158);
insert into Contem (id_spot, id_tag) values (29, 163);
insert into Contem (id_spot, id_tag) values (39, 244);
insert into Contem (id_spot, id_tag) values (26, 241);
insert into Contem (id_spot, id_tag) values (98, 165);
insert into Contem (id_spot, id_tag) values (250, 204);
insert into Contem (id_spot, id_tag) values (119, 282);
insert into Contem (id_spot, id_tag) values (153, 302);
insert into Contem (id_spot, id_tag) values (193, 214);
insert into Contem (id_spot, id_tag) values (207, 192);
insert into Contem (id_spot, id_tag) values (99, 112);
insert into Contem (id_spot, id_tag) values (124, 131);
insert into Contem (id_spot, id_tag) values (99, 185);

COMMIT;
